recursive: false
require_red_pair: true
n: 0
resize_to_target: true
target_width: 2048
target_height: 1500
score_thresh: 0.2
box_nms_thresh: 0.3
detections_per_image: 300
classes_to_keep: [1, 2, 3]
per_class_score_thresh: {"1": 0.5, "2": 0.5, "3": 0.5}
