seed: 42
k_folds: 5
num_workers: 8

classes_to_count: [1, 2, 3, 4]

score_thresh_grid: [0.15, 0.20, 0.25]

box_nms_thresh_grid: [0.25, 0.30]

detections_per_image_grid: [300]

per_class_score_thresh_grid:
  - {"1": 0.35, "2": 0.35, "3": 0.35}
  - {"1": 0.30, "2": 0.30, "3": 0.30}
  - {"1": 0.25, "2": 0.25, "3": 0.25}