seed: 42
k_folds: 5
num_workers: 8

classes_to_count: [1, 2, 3, 4]

score_thresh_grid: [0.05, 0.10, 0.15, 0.20]

box_nms_thresh_grid: [0.25, 0.30, 0.35, 0.40, 0.50]

detections_per_image_grid: [300]

per_class_score_thresh_grid:
  - {"1": 0.35, "2": 0.35, "3": 0.35}
  - {"1": 0.30, "2": 0.45, "3": 0.45}
  - {"1": 0.45, "2": 0.45, "3": 0.30}
  - {"1": 0.35, "2": 0.40, "3": 0.45}