seed: 42
k_folds: 5
num_workers: 8

# same meaning as in train config
classes_to_count: [1, 2, 3]

score_thresh_grid: [0.2]

# Post-processing sweeps
box_nms_thresh_grid: [0.25, 0.30, 0.35, 0.4, 0.45]
detections_per_image_grid: [300]

per_class_score_thresh_grid:

  - {"1": 0.40, "2": 0.40, "3": 0.40}
  - {"1": 0.45, "2": 0.45, "3": 0.45}
  - {"1": 0.50, "2": 0.50, "3": 0.50}
  - {"1": 0.55, "2": 0.55, "3": 0.55}
  - {"1": 0.35, "2": 0.50, "3": 0.50}
  - {"1": 0.40, "2": 0.50, "3": 0.50}
  - {"1": 0.50, "2": 0.35, "3": 0.50}
  - {"1": 0.50, "2": 0.40, "3": 0.50}