seed: 42
k_folds: 5
trials: 12
epochs: 10
amp: true
num_workers: 16

classes_to_count: [1, 2, 3]

val_score_thresh: 0.5

space:
  anchor_sizes:
    - [[8], [16], [32], [64], [128]]
    - [[12], [24], [48], [96], [192]]
    - [[16], [32], [64], [128], [256]]
  aspect_ratios:
    - [[0.5, 1.0, 2.0],
       [0.5, 1.0, 2.0],
       [0.5, 1.0, 2.0],
       [0.5, 1.0, 2.0],
       [0.5, 1.0, 2.0]]
    - [[0.75, 1.0, 1.33],
       [0.75, 1.0, 1.33],
       [0.75, 1.0, 1.33],
       [0.75, 1.0, 1.33],
       [0.75, 1.0, 1.33]]
  trainable_backbone_layers: [2, 3]
  batch_size: [1, 2]
  lr_backbone: [1e-5, 2e-5]
  lr_heads: [1e-4, 2e-4]
  weight_decay: [1e-4]
  detections_per_image: [300]
  box_nms_thresh: [0.4, 0.5, 0.6]